### ISSUE TITLE
Order main readme table by dandiset id

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/DANDIArchiveShowcase#7]
To aid finding of a specific dandiset, but also I noticed that when I regenerated locally (it did seem to work in the end, ~700MB total size), it generated the table in a different order. If it's ordered by dandiset id, changes in specific dandisets will be easier to see between commits (e.g. if a validation status changes between runs).

**Comment by pgleeson** [comment]
Thanks @anhknguyen96. Do you think what's on dev is ready to merge to master? 
By the way, it might be best for you to mainly work on dev, and create specific other branches for other fixes/features, e.g. test_gha for changes related to actions. pg_tests was just a branch for me to test out some quick changes. 

You will probably have to add more branches (or *) here: https://github.com/OpenSourceBrain/DANDIArchiveShowcase/blob/main/.github/workflows/ci.yml#L7, so the tests will run

**Comment by anhknguyen96** [comment]
nwb_table_readme.py is ready.
If we don't care about testing NWBE compatibility at the moment (I assume it's only after we have all the dandisets validated with nwbinspector and get a rough idea of the number of valid dandisets), get_nwb.py (download and validate dandisets/nwb files with user's inputs) and validate_and_test_nwb.py (bulk testing dandisets) are functional. I'm having problem with resolving dependency issues caused by datalad & nwbinspector in the CI runs (the latest commits in the pg_tests branch were modifying the ci.yml file to attempt at fixing those issues). In short, installations of these packages are better supported in conda environments (for example, using the streaming option in nwbinspector requires [building h5py with ROS3 support from scratch](https://github.com/h5py/h5py/issues/1712) in non-conda environments, AFAIK). If we don't have any issue with the github actions' testing environment being conda, I can try modifying the yml file accordingly. What do you think? @pgleeson  @sanjayankur31

**Comment by pgleeson** [comment]
Great. What I'd suggest is making a minimal version of the ci script in dev that just tests nwb_table_readme.py and passes and opening a PR. The rest of the scripts can be tested in time, and probably it's not an issue to use conda in the test script. If there is a specific issue/incompatibility you come across, feel free to open an issue in the appropriate repo, as these packages I'm sure will be used together by otehrs in the area.
